### ISSUE TITLE
Link to opensource-team 404's

### ISSUE THREAD

**Issue by ajnelson-nist** [usnistgov/opensource-repo#11]
Hi,

There is a link in the README to this team:

https://github.com/usnistgov/teams/opensource-team

When I visit it (authenticated to Github as my NIST self), it returns a 404 not found.

If this team exists and is private, should it be linked in the public README?

--Alex

**Comment by GRG2** [comment]
Thanks Alex,   i fixed the link in the README

**Comment by ajnelson-nist** [comment]
Fix confirmed.  Thanks!
