### ISSUE TITLE
Possibly include link to guidelines for making research software FAIR

### ISSUE THREAD

**Issue by wd15** [usnistgov/opensource-repo#5]
Here are a list of different guidelines (my preference is [Library Carpentry](https://librarycarpentry.org/Top-10-FAIR//2018/12/01/research-software/)):

  - Top 10 FAIR data and software things, https://www.rd-alliance.org/group/libraries-research-data-ig/outcomes/top-10-fair-data-software-things
 - Research Software, https://librarycarpentry.org/Top-10-FAIR//2018/12/01/research-software/
 - NLeSC FAIR-software.eu, https://fair-software.eu/
 - NLeSC howfairis, https://github.com/fair-software/howfairis
 - Data and Software Sharing Guidance for Authors Submitting to AGU journals, https://data.agu.org/resources/agu-data-software-sharing-guidance
 - PresQT applying FAIRSharing and FAIRShake, https://presqt.readthedocs.io/en/latest/
 - Registry of Research Data Repositories (also has SW locations), re3data.org/
 - Automating the Monitoring of research software FAIR metrics, https://doi.org/10.7490/f1000research.1117992.1
 - Proposal for software indicators in the Open Science Monitor (France), https://www.ouvrirlascience.fr/about-the-proposal-for-software-indicators-in-open-science-monitor-3/
 - From National Plan for Open Science in France (2021-2024) THEME THREE: OPENING UP AND PROMOTING SOURCE CODE PRODUCED BY RESEARCH, https://www.ouvrirlascience.fr/second-national-plan-for-open-science/
 - Turing Way, https://the-turing-way.netlify.app/welcome
 - Software Citation Guide, https://doi.org/10.12688/f1000research.26932.2
 - MIT libraries Software Citation and Publishing , https://libguides.mit.edu/software
 - MIT workshop: Managing your research code, https://www.dropbox.com/s/gukkthqzcuea1kr/MgingCode_Slides_MIT.pdf?dl=0
 - Managing Research Software Projects, https://swcarpentry.github.io/managing-research-software-projects/
 - UK SSI Guides for several target groups, https://www.software.ac.uk/resources/guides
 - Chorus Software Citation Policies Index, Software Citation Policies Index - CHORUS (chorusaccess.org)
 - Software Discovery through registries, https://softdev4research.github.io/4OSS-lesson/05-use-registry/index.html
 - Awesome Research Software Registries, https://github.com/NLeSC/awesome-research-software-registries/blob/main/README.md
 - Codemeta, https://codemeta.github.io/
 - Software metadata extraction framework (SOMEF), https://github.com/KnowledgeCaptureAndDiscovery/somef/
 - Good enough practices in scientific computing, https://doi.org/10.1371/journal.pcbi.1005510
 - "TU Delft Guidelines on Research Software: Licensing,  Registration and Commercialisation", https://doi.org/10.5281/zenodo.4629635
 - Choosing a Repository Manager - for TU Delft Researchers, https://doi.org/10.5281/zenodo.4710206
 - Citation File Format, https://github.com/citation-file-format/citation-file-format
 - Software REUSE Specification – Version 3.0, https://reuse.software/spec/
 - Helmholtz Guidelines for Sustainable Research Software , https://gfzpublic.gfz-potsdam.de/pubman/faces/ViewItemOverviewPage.jsp?itemId=item_4906899
 - Checklist for Helmholtz Guidelines, https://gfzpublic.gfz-potsdam.de/pubman/faces/ViewItemOverviewPage.jsp?itemId=item_5007561
 - DLR Software Engineering Initiative, https://rse.dlr.de/01_guidelines.html
 - NIH Best Practices for Sharing Research Software, https://datascience.nih.gov/tools-and-analytics/best-practices-for-sharing-research-software-faq

**Comment by tkphd** [comment]
* Awesome FAIR Data <https://github.com/Materials-Data-Science-and-Informatics/awesome-fair-data>

**Comment by tkphd** [comment]
* DANS FAIRaware "tool" (really a quiz/checklist), <https://fairaware.dans.knaw.nl>

**Comment by wd15** [comment]
Probably nice to maintain this list in a markdown file in the repository to keep as a reference.
